### ISSUE TITLE
Make character codes be more keyboard friendly

### ISSUE THREAD

**Issue by gytdau** [DavidLGoldberg/jumpy#105]
The codes go alphabetically: `aa`, `ab`, and so on. However, you might want to instead consider the keys that the hands touch in a more neutral position, like the home row. Using those keys first would be more comfortable, reducing stretching, and would probably make jumping faster.

**Comment by DavidLGoldberg** [comment]
This is a good idea, and been discussed in the past, but unfortunately is probably pretty low down on the list of things I would work on anytime soon.

My next initiative is getting some architecture changes in place to enable jumping to items in the tree view:
https://github.com/DavidLGoldberg/jumpy/pull/106

After this I want to convert a bunch of the above into elm for the core components for stability and so I can ideally share and port a bunch of the code to VS Code as well. 

The idea of home keys works great for things like vimium:
https://chrome.google.com/webstore/detail/vimium/dbepggeogbaibhgnhhndojpepiihcmeb?hl=en
(if you use vim and like Jumpy, I recommend trying it out I love it).

The difference is there are usually far less links on a page than text.  How do you even know what's more likely important, you could do heuristics.  Or you could start with home keys and work up but I think there's a level of comfort of putting keys together.  It assists when you type a letter to make sure you're honing in in the right region, and didn't make a typo and backspace out.

BTW, for example, I'd much rather work on performance of the decorations rendering than attack this.

But if someone submits a PR and it fits in real well, or an option etc, I would consider taking a look, but no guarantees as I'm not too into it :\

I'm going to close this as an issue from my list, but feel free to keep the discussion going on the thread!

Thanks for your interests / thoughts!  Keep them coming!
