### ISSUE TITLE
suggestion: activate on only current line?

### ISSUE THREAD

**Issue by ericychoi** [DavidLGoldberg/jumpy#107]
I do love the concept of jumping around the screen only using keyboard; unfortuntely I had to stop using this since it was getting little too slow for me (I haven't tried the latest version though).  

An idea to speed things up a little is to maybe activate jumpy only on the current line so that it doesn't have to parse the whole contents?  This way I can combine it with ctrl-G to jump to the place I want in 2 key strokes.

Thank you for the awesome app!

**Comment by DavidLGoldberg** [comment]
You should probably invest in learning vim for things like that.  Atom has vim emulation by way of the  `vim-mode-plus` package.

I have no plans do line only jumping.  Actually recent changes to atom has made jumpy noticeably faster (without my doing anything).

I'm also working on a new rewrite that seems to help a bit as well. 

Might want to give it a shot now or in a few weeks!

Thanks for the interest!  Also, how old is your machine, mine's a few year old macbook pro.

Also, if it's REALLY slow, I wouldn't mind taking a look at what you have installed, maybe there's a conflicting app, things like that have happened before.... Atom package env isn't a perfect science yet...(probably never will be!)  Going to close the issue, but feel to keep the thread going!

**Comment by DavidLGoldberg** [comment]
FYI, towards the contrary I have more plans by way of getting more jump points, end of long words / end of lines, some symbols etc.
