### ISSUE TITLE
Focus only on active window/panel

### ISSUE THREAD

**Issue by yangwao** [DavidLGoldberg/jumpy#109]
When I have 6 windows with code opened, it will highlights also in other windows.
That's good, but somehow it takes a while to generate shortcut labels.

What if I could just enable it for one window or only one panel with tabs?
Maybe it could make things faster?

Btw, great work, thanks! 🤗

**Comment by DavidLGoldberg** [comment]
Thanks for the issue!  That's not a bad idea or anything but I think I'd rather not build / support the issue, but rather work on performance.

With the current version of Atom / Jumpy I've only been seeing the lag with a good number of labels...

I'll chalk this up to performance is really important, so I should work on improving that.

**Comment by DavidLGoldberg** [comment]
https://github.com/DavidLGoldberg/jumpy/issues/110
