### ISSUE TITLE
Jump to `letter` like ace jump (emacs)

### ISSUE THREAD

**Issue by am** [DavidLGoldberg/jumpy#112]
Hi,

I was looking for a port of ace jump to atom that works like the emacs ace jump and I found your project :)

One thing I noticed and it bothers me a little is that there is no initial input letter to filter my jump.
When using emacs ace jump you do the following:

1. activate ace-jump
2. input the first char of the word you want to jump to
3. do the jump pressing the key comb

I find this less noisy since usually only a few jump options are provided. 

Is there any way to achieve this using Jump?

Many thanks

**Comment by DavidLGoldberg** [comment]
Nope. Sorry. Actually a lot of us find jumpy easier cognitively (especially
with vim bindings).

But if I was using emacs binding personally I might want something more
like ace jump...

There were some experiments done by some people into like fuzzy search for
the chars  (stand alone packages) but I think those were mostly abandoned.

**Comment by am** [comment]
Hi @DavidLGoldberg, thanks for the prompt reply. I guess that what I propose could be easly be extendend from jump. If I have something done I will PR.

For now I'll close this since the question is already answered.

Cheers
