### ISSUE TITLE
How to scroll down?

### ISSUE THREAD

**Issue by Nxt3** [DavidLGoldberg/jumpy#113]
Maybe I'm missing something, but how do you jump down past the visible view? What if I need to jump down past what's visible? Do I have to use the mouse?

**Comment by DavidLGoldberg** [comment]
Not in scope for the package. You use some other technique.  Vim or Search
etc. Think of Jumpy as just a way to simulate left mouse clicks (kind of).

**Comment by Nxt3** [comment]
Alright, thank you!
