### ISSUE TITLE
OMG Wow!!!

### ISSUE THREAD

**Issue by gee-forr** [DavidLGoldberg/jumpy#119]
Hi @DavidLGoldberg - I just updated to 5.x. The improvement is speed is staggering. The jumping on trees is innovative and useful.

It's gonna take a little time to get used to showing all jump tags as soon as jumpy is activated, but in the long run this might be a better way to use it.

Overall - thank you so much for this update. It's highly appreciated. You, sir, have left no ass un-kicked in this update.

Please close this issue once you've had a chance to read it.

**Comment by DavidLGoldberg** [comment]
Thanks @gee-forr !

Glad you're digging it!  The real performance of the decorators in Atom is a little hard to measure especially across releases, but this release *seems* a bit faster for me too as well.  Performance wasn't the real intent behind the rewrite but yeah so far so good.

Make sure to get 5.0.1, I upgraded to elm .19 which cuts down on a lot of excess and is ya know, of course the new hotness.

Thanks for the feedback!
-David
