### ISSUE TITLE
Performance degradation after a while

### ISSUE THREAD

**Issue by despairblue** [DavidLGoldberg/jumpy#43]
The below screenshot is clicking in a source file to move the cursor. It takes over a second, most time is spend in some jumpy event handlers.

![screenshot from 2015-01-06 18 05 55](https://cloud.githubusercontent.com/assets/927609/5632445/1521eebc-95cf-11e4-8f07-1d8c5d0395e7.png)

## Repro Steps

1. Keep jumpy using for a while

## Command History

```
     -0:27.6 pane:became-active (atom-pane.pane.active.with-minimap)
     -0:27.6 pane:became-inactive (atom-pane.pane.with-minimap)
     -0:02.4 command-palette:toggle (div.settings-view.pane-item)
     -0:00.0 core:confirm (input.hidden-input)
     -0:00.0 bug-report:open (div.settings-view.pane-item)
```

## Versions

* **Atom:**       0.166.0
* **Atom-Shell:** 0.19.4
* **OS:**         linux 3.14.26-1-lts
* **Misc**
    * apm  0.116.0
    * npm  1.4.4
    * node 0.10.33
    * python 3.4.2
    * git 2.2.1

---

<small>This report was created in and posted from the Atom editor using the package `bug-report` v0.5.3.</small>

**Comment by DavidLGoldberg** [comment]
Thanks so much.  Whole new version coming soon.

Do you have shadow dom enabled btw?

**Comment by DavidLGoldberg** [comment]
Interesting that it's in the clearJumpMode, I'll run it through a few iterations to test it.  Might not be there in my 2.0 branch (hopefully)

**Comment by DavidLGoldberg** [comment]
@despairblue I don't currently have a good linux box readily available..that is with X of course ;)

I just released a 2.0.0 that handles the new architectural changes in Atom towards shadow dom.  Almost every line had to change as I removed deprecated functions.  I think this problem may very well have gone away.  I have yet to reproduce it.  Could you let me know if I can close this?

Appreciate it! Thanks!

**Comment by despairblue** [comment]
Thanks for jumpy and the quick response :)

The shadow Dom was disabled. I'll test the new version with the shadow Dom
enabled.

**Comment by DavidLGoldberg** [comment]
FYI, shadow dom was supposedly made default in .166 Atom ......so, maybe the fact it was still set *off* on your box caused some kind of problem? (just speculation!)  They just fixed a bug in config's being reset (that was really annoying) so maybe it had some residual damage? heh.

**Comment by despairblue** [comment]
Yep, it was on by default, but I disabled it specifically 'cause using jumpy was more important for my workflow than preventing style pollution. I don't think the config reset bug had anything to do with it...maybe the fix had smth to do with it, though I couldn't think of a connection.

Just testing jumpy 2.0, it's actually faster than before the performance degradation...impressive :smile: 
I'll keep using it and report back in a while...

**Comment by DavidLGoldberg** [comment]
Ok, awesome.  Thanks!!

BTW, I woke up a little early and just released a 2.0.1 because I found that the scroll event stuff broke with new Atom.  Was a pretty easy fix.

**Comment by despairblue** [comment]
Ok, I suppose this is fixed. Haven't run into it again. Thanks man, great plugin!

**Comment by DavidLGoldberg** [comment]
Thanks for raising this!

**Comment by DavidLGoldberg** [comment]
Leaving this one closed and new one open as it contains new info.

**Comment by despairblue** [comment]
:+1:
