### ISSUE TITLE
Enter the first 2 chars to move to a word

### ISSUE THREAD

**Issue by assemnical** [DavidLGoldberg/jumpy#50]
The behavior is based on vim-sneak https://github.com/justinmk/vim-sneak. Lets say I want to move to a word called "Flight", I would enter fFl (I remapped this plugin like suggested to f) and move to the first occurrence of Fl and advance to the next occurrence with ; or go back to the previous one with " . The navigation would be much faster than it is now ( at least for me as I don't have to look up tiny letters to press). Is this mode already possible or would I have to implement it?
Best

**Comment by DavidLGoldberg** [comment]
I think that could be a made into a different plugin.  I don't think I want to support that per se.  Do you use vim-mode? it sounds a lot like / -> 'Fl' -> enter.  If not you can do that with cmd+f -> Fl -> enter (obviously slightly longer).  Is vim-sneak just to remove the enter?  I mean with vim search you can just hit 'n' to go to the next..

The whole point of jumpy is to avoid cycling through results and go exactly where you're looking.  It's just to replace the mouse.  Works best with big monitors and multiple panes etc.

**Comment by DavidLGoldberg** [comment]
Please feel free to convince me to build and or support it though :)

It's also of course very easy to add in optional behavior with Atom's settings...

**Comment by assemnical** [comment]
Yes I only use vim/vim-style editors and the behavior is pretty much as you described 
```
/Fl<enter> 
```
but quite faster as you mentioned (besides that you don't have to leave your homerow). 
I tried vim plugins like yours but it never speed up my workflow. Looking for characters just doesn't work for me, I'm faster cycling some occurrences if necessary (tbh it doesn't happen that often, two chars seem to be a quite good id). I'm quite new to Atom (and coffescript) but it seems this should be a good starting point for a new package. Thanks for your feedback/help!
