### ISSUE TITLE
Not all configs present if opening up preferences before a jumpy toggle has been performed

### ISSUE THREAD

**Issue by DavidLGoldberg** [DavidLGoldberg/jumpy#53]
I never knew this was an issue.  I wanted to move some things up in activate anyway.

**Comment by DavidLGoldberg** [comment]
This is so weird.  Apparently an issue in Atom.  I would have to remove the activation event and handle loads.  Could effect performance of users' atom loads.  Not going to risk it.  I'll wait for Atom to fix this.

**Comment by despairblue** [comment]
For reference: https://github.com/atom/settings-view/issues/356

**Comment by DavidLGoldberg** [comment]
Thanks.  Yeah I thought it specifically wasn't it "settings-view" oops.  Thanks for locating that.  Kind of crazy huh?

**Comment by DavidLGoldberg** [comment]
I like how that's another virtual vote on that issue via referencing ;)

**Comment by despairblue** [comment]
That was the plan :wink:
