### ISSUE TITLE
Performance degradation

### ISSUE THREAD

**Issue by despairblue** [DavidLGoldberg/jumpy#54]
After working with with two panes open for a while (with 2 medium sized files open, each ca. 150 LOC) I experienced the same performance degradation as in #43, though this time it's `atom/resources/app/node_modules/event-kit/lib/emitter.js` (`modules.exports.Emitter.on`) eating up all the CPU. So this could also be an atom problem.

This only happens when clicking around in the files, I have to wait 1 or 2 seconds until the cursor is placed. Keyboard navigation is snappy as usual.

![screenshot from 2015-03-19 14 36 45](https://cloud.githubusercontent.com/assets/927609/6731466/62254494-ce45-11e4-9a7b-fa169c967e92.png)

![screenshot from 2015-03-19 14 27 52](https://cloud.githubusercontent.com/assets/927609/6731364/c80cf726-ce44-11e4-8451-9919995355fc.png)

## Command History

```
     -0:06.1 selection:changed (atom-text-editor.editor.is-focused)
     -0:05.8 pane:active-item-modified-status-changed (atom-pane.pane.active)
     -0:03.4 core:select-all (atom-text-editor.editor.is-focused)
     -0:03.4 selection:changed (atom-text-editor.editor.is-focused)
     -0:01.9 core:backspace (atom-text-editor.editor.is-focused)
     -0:01.9 cursor:moved (atom-text-editor.editor.is-focused)
     -0:01.9 selection:changed (atom-text-editor.editor.is-focused)
     -0:01.6 pane:active-item-modified-status-changed (atom-pane.pane.active)
     -0:01.5 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:00.0 core:confirm (atom-text-editor.editor.mini)
     -0:00.0 bug-report:open (atom-text-editor.editor.is-focused)
```

## Versions

* **Atom:**       0.187.0
* **Atom-Shell:** 0.21.3
* **OS:**         linux 3.14.26-1-lts
* **Misc**
    * apm  0.142.0
    * npm  2.5.1
    * node 0.10.35
    * python 2.7.9
    * git 2.3.3

---

<small>This report was created in and posted from the Atom editor using the package `bug-report` v0.6.3.</small>

**Comment by DavidLGoldberg** [comment]
Hey @despairblue , thanks for bringing this up.  Just today I noticed some 2 pane slowness.  I'll take a look at it ASAP and hopefully I'll have a fix by the weekend.  I guess the stack you saw is something like in #43 so you knew it was Jumpy right?

**Comment by despairblue** [comment]
Yeah, also the Jquery.event.distpatch in the top-down-profile taking up 53% of the CPU comes from jumpy :)

**Comment by despairblue** [comment]
This also happens when working with a single pane and applies to all of atom: The below chart demonstrates a click in the settings view, clicking in the tree view produces the same thing. Some anonymous function in jumpy (that can't be optimized for some reason) takes up to 700ms per click. :(

![screenshot from 2015-03-26 14 34 33](https://cloud.githubusercontent.com/assets/927609/6847246/559c965c-d3c5-11e4-8b86-b3b480872b84.png)

**Comment by despairblue** [comment]
Btw, https://github.com/DavidLGoldberg/jumpy/blob/master/lib/jumpy-view.coffee#L200 is called 46 with every click. That and that it's not optimizable is probably why it accumulates so quickly.

**Comment by DavidLGoldberg** [comment]
So, @despairblue Thanks so much for all of your help!  I almost sent you an update message this morning saying it was on it's way.  Finished it last night just had to work out a test etc...

Not only did I catch that one, but maybe a bigger issue with scrolling.  Also, I got smarter about short circuiting and I think clean up.. Geez.  It's funny the jumps happen so relatively quickly, I had no idea I was slowing down other stuff.  This sucker should be a LOT more optimized now.  One day I'll maybe take another look at it with a few guys and have a code review etc.  Please feel free to beat up on it some more :+1: :-)

So I'm *pretty* sure I solved the same issue you're referring to but maybe there's something else out there or another bottleneck I can improve.  Please let me know.  Also, I'd really love it if you could do your same analysis again and make sure I did fix at least *something* :)  I'll settle for 3 steps forward 1 back, hah.

**Comment by despairblue** [comment]
After using atom with jumpy for a couple of days I'm pretty sure you squashed this :smiley: :clap:

**Comment by DavidLGoldberg** [comment]
:tada: lol
