### ISSUE TITLE
vim mode keymaps dont work all the time

### ISSUE THREAD

**Issue by kyriacos** [DavidLGoldberg/jumpy#56]
I tried removing all my other keymaps and just adding the one recommended in the README. 

Unfortunately it works as soon as i save the keymap.cson file and then it stops when i open a new file in the editor.

I tried it a bunch of times and i can't figure out why. Shift-enter works just fine.

Is this related to jumpy or the vim-mode plugin?

Thanks!

**Comment by DavidLGoldberg** [comment]
Hmm.  I could take a look at that flow later (I'll leave this open).

Did you try control+alt+command+l (l as in reLoad) (that's what it is on a mac) to reload Atom?

**Comment by DavidLGoldberg** [comment]
Also, you're a new Jumpy user right?  Or was this working earlier?

**Comment by kyriacos** [comment]
@DavidLGoldberg new Jumpy user. I just decided that shift-enter doesn't map well in vim-mode as i am a vimium user too :)

I closed and re-opened atom would reloading instead make a difference?

**Comment by DavidLGoldberg** [comment]
If you're on a mac and you still have the Atom bar at the top, it might not have reloaded.  Please try 'View' -> 'Reload'.

At that point it should work here after.  I was able to reproduce what your'e seeing after the first turn on from within the file.  I always reload after making changes to that file as clearly not all the results are as they seem live reloaded.

That said I might be able to improve this.

**Comment by kyriacos** [comment]
I'll give it a go and let you know. Thanks for looking into it!

**Comment by DavidLGoldberg** [comment]
BTW, I gave a quick look and I think I found one of the causes...I'll have to throw some time at it but I think I might have a fix for it.

Thanks!

**Comment by kyriacos** [comment]
@DavidLGoldberg Thanks! I did try it out. And it works after reloading. I haven't managed to break it again.
