### ISSUE TITLE
Multiple match patterns - use different pattern deppending how it is called

### ISSUE THREAD

**Issue by romgrk** [DavidLGoldberg/jumpy#57]
This is a request for enhancement.
What I would like to see is something that ressembles Vim's EasyMotion plugin, in the sense that it has multiple patterns instead of one. e.g: 

> **EasyMotion + w**    creates labels on words
**EasyMotion + j**      creates labels on lines

**Comment by DavidLGoldberg** [comment]
Few thoughts...

I had the idea for Jumpy before I ever knew EasyMotion existed (although I'm a longtime Vim user).  When I saw / tried EasyMotion, I thought it was way too difficult.  They made it better in recent versions, but I still think there is too much involved.  Prior to the Atom version I decided to not mirror EasyMotion / make it as complex.

I *do* have plans to add labels for newlines.  I see no advantage to ever turning off word labels.  I want to supplement the existing labels with end of lines and new lines.  I also want to better label symbols for C style symbols / Lisp variants etc.  There are other issues related.  @willdaddy has a related pull request.

I pulled @willdaddy's PR (in a branch) but we have plans to abandon some of his direction of handling more with the regex and actually lock down the regex provided we account for the newlines etc.

Why don't I want 2 keys?  I don't want a user to have to think of where to jump before activating.. If they know they have to jump they should fast twitch jumpy mode and jump anywhere.  Know what I mean?  Any advantages / reasoning I'm missing?  Similarly I don't like the idea of clicking one character and waiting to read the next.. The people that I have spoken to about this and tried both tend to agree simple is better...

If you've been using EasyMotion for years and need that muscle memory, there is an EasyMotion package... I don't know how active it is:
https://github.com/adrian-budau/easy-motion/issues

Also, feel free to fork or steal from Jumpy if you want to make this!

That said the new lines / end of line tweaks are next on my list for this, although I take pull requests too :)

**Comment by DavidLGoldberg** [comment]
I closed it, but feel free to keep the discussion going!

**Comment by romgrk** [comment]
I get your point, that having 2 or more keys might not feel as efficient, although I was thinking more of some way of customizing Jumpy, in the case that the user wants to, and not as a default.
(In general I think any package should provide as much customization options as possible)

>  If they know they have to jump they should fast switch jumpy mode and jump anywhere. Know what I mean? Any advantages / reasoning I'm missing? Similarly I don't like the idea of clicking one character and waiting to read the next..

Both *Jumpy* modes would be activated by a different shortcut. e.g.

    alt-w   creates labels on words
    alt-j   creates labels on lines 


On a different subject, wouldn't it be interesting to have close-to-cursor labels labbelled differently? For example, they could have a single letter label instead of 2 letters. Labbelling would go as follow:

    a, b, c, ..., y, z, aa, ab, ac, ..., ay, az, ba, bb, ...

If you would take PR for any of these, please let me know, I would be interested in creating discussions/PR around these subjects.

**Comment by DavidLGoldberg** [comment]
I would be very interested in all discussions!

I can't guarantee accepting a feature, aka customization if it adds overall complexity to the app, or more difficult maintenance :-\
I don't agree that every package should provide as much customization as possible.  We have to worry about "feature creep", and balance for features that people actually use.  One thing to keep in mind is that Atom is still not yet 1.0.  When they upgrade things break.  They have broken before and I've had to do almost complete rewrites.  If Atom were more stable or I had more people involved we could *probably* offer more "customization" (it's a threshold / rate balance kind of thing right?).  Although I still wouldn't want to be too frivolous there either.

Also, your 2nd idea interests me more for sure..I've toyed with some ideas there, but haven't landed on anything very cool. I don't like the idea of waiting and reading again for further "accuracy".

BUT if you can come up with an optional drilling to 2nd character.. Of course this has to work with vim-mode enabled and disabled...In all of the vim-modes modes it currently works with... (all pretty much to my knowledge)

Aside (probably unrelated): Another gotcha area for this code base is code folding and word wrap FYI.
