### ISSUE TITLE
Beacon broken as of 0.208.0

### ISSUE THREAD

**Issue by DavidLGoldberg** [DavidLGoldberg/jumpy#64]

**Comment by seivan** [comment]
Yeah, I can't see the beacons either.

**Comment by larsbijl** [comment]
same thing here.

I am running both ubuntu 15  and centos 7.

**Comment by DavidLGoldberg** [comment]
Yeah, so, kind of busy but plan to take a look at it soon, luckily it's not too critical, it was actually not working for quite a while, although I much prefer to have the beacon especially with pairing.  It feels like they keep changing everything.  Hopefully more of this will be locked down with 1.0.  I am going to try to to build the labels / beacon with

"markers", "decorations", and "flashes" hopefully performance will be ok, might be able to drop some code.

**Comment by seivan** [comment]
Sounds good! Much obliged.

**Comment by larsbijl** [comment]
As it stands the plug-in is not usable for me at least on Linux,  other than a message at the bottom saying Jump mode! no letters appear at all.  this is happening both in contrast mode and in not contrast mode

**Comment by DavidLGoldberg** [comment]
@larsbijl Ok, I misunderstood your issue earlier.  So my jumpy is completely working / functional.  Are you on the newest Atom?  What version.  The only thing missing is a beacon which just flashes red after a jump (totally not critical at all).

You're not seeing labels?

@seivan your jumpy is otherwise working correct right?

If it's not please try making sure you have shadow dom selected in options (I've abandoned non shadow dom some time ago, as it's now the default).  Also, try

`apm install jumpy' again

and restart all of your atom instances after upgrading to the newest version...

**Comment by DavidLGoldberg** [comment]
I'm going to put my `pretty-minor` tag on this one, so as to denote that anyone who is seeing your mentioned issue, should start a new separate issue.

**Comment by seivan** [comment]
@DavidLGoldberg Reinstalling actually fixed it. Thanks again!

**Comment by larsbijl** [comment]
0.201.0 i was on, now i'm on 0.210.0 and it seems to be working :)
thanks!
