### ISSUE TITLE
Refactoring, Performance improvement

### ISSUE THREAD

**Issue by t9md** [DavidLGoldberg/jumpy#65]
This is not issue. 
Thanks for useful packages.

I want to share my experiment to Jumpy code.

Today, I started to investigate your package( mainly to get idea for my own package ).
And did some experiment, like bellow

- delete unnecessary observeTextEditors()
- use native DOM manipulation than jQuery's one for performance.
etc, etc

Although my experiment is in progress, I think performance was greatly improved.

https://github.com/t9md/jumpy/tree/experiment

[ADD]
Noticed what I thought performance slowness was because of animation effect set in style.
This package is fast move to target position, I think its better to make animation optional and no animation by default.

**Comment by t9md** [comment]
My rewriting process almost done.
I can send pull request but I'm not sure its appropriate because

- Code changed completely so, too big to simple PR.
- I removed not essential(at a glance) code, and changed Style(removed animation).
- Spec(test) broken. It need be rewritten.

**Comment by DavidLGoldberg** [comment]
Very excited to read the stuff *some* sounds like stuff I was looking at... I'll check it out in the next few days... This should be a pull request so we can start a good thread sounds great!

**Comment by t9md** [comment]
Thanks.
After I wrote above comment, I tried rewriting again using [custom Element](https://github.com/t9md/jumpy/blob/experiment/lib/label-view.coffee).
It seem work well.

**Comment by DavidLGoldberg** [comment]
@t9md You should open a pull request.  A pull request doesn't mean it's ready to be merged in yet.

See:
https://help.github.com/articles/using-pull-requests/

It answers some of the above questions.

Also, I've been a little bit busy, but I'll try to check out the code this weekend.  

Did you utilize the Atom decorations?  From a quick peek, no right?

They have a notion of markers and decorations I've toyed with the idea of trying to use.  In general I've found no real performance issue with Jumpy, on systems I've used it it's been sub human noticeable times (used console.time to check etc).  So i've focused efforts elsewhere, (honestly just keeping up with the Atom changes prior to 1.0 was a substantial percent of my efforts heh.

That said, I'm totally up for pulling in better / cleaner more performant code!

I just took a quick peek at your code.  First thoughts are it looks clean as heck.  I've been thinking of splitting some code into diff files etc.. I like how you made it slightly more OOish from what I can tell.  My quick assessment is this stuff is probably super awesome.  I might be more for pulling in parts at a time though?  I notice some areas are just completely changed, not sure why.

BTW, I would imagine most of the tests should still work if the features are there?  There are some tricks to get through the shadow stuff.. .shadowRoot etc.. I can help you with those.  Again, I just did a quick glance through of shape of things, definitely up for incorporating some in.  I'd rather us look at the marker/decorations stuff also though.  You should also check out the other PR that's open.  I want to eventually get to that as well.  Doing refactors / features should be easier again now that Atom 1.0 is more stable (or at least supposed to be)

**Comment by DavidLGoldberg** [comment]
Also, after we take this a little further, I might @ mention a few of the other previous contrib / issue creators to get their take / review too.

**Comment by t9md** [comment]
Thanks, I know how to send PR, OK I will send PR.
Since I drastically changed code base, I originally didn't meant to send PR.
The rewriting purpose is mainly to make me understand how this label jump system works.

I was vim user, and I created similar plugin in VimScript before, and wanted to port to this feature to Atom.
For this reason, I changed code too aggressively, and some feature might broken.
But I currently don't have motivation to improve further since its' just experiment.

For decoration, I didn't use in jumpy experiment.

**Comment by DavidLGoldberg** [comment]
Oh, btw, yes I've always wanted the ability to turn off the animation, it used to be very easy to do in the stylesheet...

I may or may not have had it in the readme at one point...

I don't know off the top of my head right now how easy those overrides are to do with current shadow dom etc.  If anything I can dynamically add it / remove it in code with an option I totally agree!! 

BTW, Yeah, over time I've scaled down the animation making it barely there, but I still think it's nice, I don't personally have an issue with the perf, but yeah I could see wanting to turn that off especially on slower machines, or with a million packages installed etc!  I'll definitely try to work that in.

Random aside, I'd like to get my beacon back on and working, helps a lot while pair programming.  It was broken for a while, and right when I fixed it, they broke it again (pre 1.0) when they changed their rendering to like block level updates or something.  If you have any ideas or know *exactly* why it stopped working and assume that I already know, well no, I don't ;-)  Not yet at least I haven't spent too much time looking at it yet.

**Comment by DavidLGoldberg** [comment]
Yeah, so even if you're no longer motivated, I will take a look and try to merge your PR in and get you on the contrib list!  I really appreciate you letting me know and contribing etc.  I'll try to ping you only for some insight etc... Just out of curiosity are you trying to replicate easymotion or whatever it is verbatim?

I've always thought those plugins were too complicated :-p 

Feel free to @ mention me if you have any questions or think I can help.  Also, you of course know about https://discuss.atom.io/ right?  It's super useful.

**Comment by t9md** [comment]
The one of reason I concerned about jumpy's performance is I read [this](https://news.ycombinator.com/item?id=8054283) article.
I didn't read thoroughly. But I felt jumpy was slow at first glance, but while I rewriting code, I finally noticed, what I felt slowness is caused by style animation.
Maybe HN's guy misunderstood this slowness is slowness of Atom itself.

For making animation optional.
I think simply create configuration option, and adding style class based on animation is enough.
May be you need two label style (one is for non-animation, other is with-animation.) and no-anomation should be default to avoid people like HN' guy or me misunderstood its performance problem.

For beacon, I'm beginner of HTML and css, so I can't understand your beacon's mechanism.
But I use decoration flushing many places in my packages.
like my cursor-history,  toggle, clip-history.
Those package allow configuration option to enable landing flashing decoration.
I believe purpose of beacon is same.


Use configuration,

**Comment by DavidLGoldberg** [comment]
Hah, yeah, I was thinking of doing a new HN show :(  That guy doesn't say Jumpy is bad, or even that it slows it down, he actually says the opposite but, yeah maybe it's time for me to make a new one hah.

I'll definitely add in the option to turn off the animation.  But if you could notice it, I'm a little suspicious that maybe something *was* actually slowing down on your machine.  FYI, I had sub 25 ms loads on my end with console.time. (Actually I don't remember the exact ms, but it was sub whatever the oculus rift guys were saying was humanly noticeable heh).

Oh your package is live?  Feel free to link it here!

**Comment by DavidLGoldberg** [comment]
I found your quick-highlight it looks AWESOME. I had something similar in sublime back in the day, didn't use it much, don't remember it handling multiple sets, and counts etc.. Always wanted more like this.

So, I just installed it with your vim-mode aliases.  This is like the greatest thing ever.  This will change how I code, genius. Great hotkey choice btw, super simple / elegant!

BTW, quick suggestion, you should probably set up the github link option to link to the atom.io page.  A lot of other packages do this and it makes it easier than have to guess name etc.

**Comment by t9md** [comment]
Thanks for good suggestion, I'll do that.

For HN news, sorry I misunderstood article, I'm not english native, and hard to read long thread.

For package I'm planning is porting my [vim-smalls](https://github.com/t9md/vim-smalls) to Atom.
Its search and jump cursor positioning package.
I believe its will be achieved by adding small code to my experiment on jumpy.

Thanks for kind feedback to my quick-highlight, its also might helpful while you do pair programming.

**Comment by t9md** [comment]
Just info, I've released my own cursor jumping package [smalls](https://atom.io/packages/smalls]) just now.
Its greatly based on jumpy experiment work.
Thanks for your preceding great work, thanks again!!.

**Comment by DavidLGoldberg** [comment]
:)

Now we can't be friends ;) JK!  I still have to try to find some time to get in some of your arch changes!

BTW, do you have a little beacon / flash when you jump?  I have to check it out.  I have to fix mine.  It's kind of crucial for the next 2 packages I'm going to create.  I'll @ mention you when I get moving on them :)

-David

**Comment by DavidLGoldberg** [comment]
Also, I'm going to add a link to your project next time I edit / push the readme too!

**Comment by t9md** [comment]
Yes ;). Mine is not beacon, simply flashing word under cursor when landing, but its same purpose to beacon.
I myself considering bouncing chosen label.

**Comment by DavidLGoldberg** [comment]
Yeah, that's a cool option too.  BTW, in the off chance, you don't know.  You *do* use vimium for chrome right?  I discovered it after I launched Jumpy hah!  Turned out they did a lot of the same things.. space to cancel etc.  I don't think they do my backspace thing yet..I want to contribute to that to see if I can help him navigate into shadow dom.  Some of the shadow piercing features are about to be pulled from Chrome however...(annoyingly IMO).

**Comment by philllip** [comment]
Great plugin. Will help my workflow a lot.

One thing on this discussion, when I first installed it and immediately tried it, it was quite laggy. It would take 5+ seconds to show shortcuts. Then I closed and opened Atom and it was much faster. I'm the kind of person who can't work if there is lag so I'm glad I tried closing/opening Atom otherwise I would have dropped using this.

The files I tested on are not large and I'm on a bulky MB pro. Just a heads up that I had to reboot Atom for it to be free of lag. Perhaps other people are having this issue?

Otherwise great work. I really like it! Jumping across panes is supppper fast now! :smile: :+1: Keep it up.

**Comment by DavidLGoldberg** [comment]
Thanks, read this the other day, sorry forgot to get back to you... There's a new issue reported...one of the last patches to Atom core really slowed all of the respective times down like 10x.... So hang tight I'm working on a branch that should use markers / decorations and the performance from what I have so far is much better.  Some of the options weren't available when I started Jumpy.  I hope to release it this weekend.

**Comment by philllip** [comment]
Awesome, no problem. I have used it when it was nice and snappy and it's such a time saver so I'll wait patiently :+1:

**Comment by DavidLGoldberg** [comment]
Sorry a little delayed I've really wanted to wrap up (just launched!):
https://atom.io/packages/qolor

I'll return to this performance branch for jumpy and take a look at it tonight and tuesday night!
