### ISSUE TITLE
Jump to ends of lines and empty lines

### ISSUE THREAD

**Issue by willy-vvu** [DavidLGoldberg/jumpy#68]
I'd totally dig this feature. Unfortunately, using `^` or `$` by itself in the regex freezes Atom.

**Comment by DavidLGoldberg** [comment]
Agreed.  On the todo list.  I'm closing this as it's well documented as a desired feature in at least 2 of the other issues.  Vote heard!

(fyi, also blank newlines)

**Comment by DavidLGoldberg** [comment]
Thanks for posting btw.

**Comment by DavidLGoldberg** [comment]
More discussion can be found in one of the pull requests btw as well, if curious.
