### ISSUE TITLE
Show letters in uppercase while requiring downcase input?

### ISSUE THREAD

**Issue by endrebak** [DavidLGoldberg/jumpy#71]
Uppercase letters are easier to distinguish between and are less used in code so they will stand out more from the surroundings.

Would you consider implementing a feature to show the match pattern in uppercase while only requiring lowercase input?

**Comment by endrebak** [comment]
Closing this since I have decided to wait a bit with trying `atom` again until some key packages are in place, so I am not personally interested. It might be a good idea though.

**Comment by DavidLGoldberg** [comment]
The chrome extension vimium does this.  Several people with regards to Jumpy have said they thought it would be a little bit of cognitive dissonance as what you see is not what you type.  Furthermore a more practical reason is that I have a (mostly hidden) feature, that on for example big screens, beyond the zz, I start labeling in Upper case for example Aa and aA, I forget which I do first, it also goes to AA and ultimately ZZ.  This is more prep for large 4K screens etc.
