### ISSUE TITLE
After changing the keybindings, jumpy only works once with them

### ISSUE THREAD

**Issue by endrebak** [DavidLGoldberg/jumpy#72]
These are my settings:

```
'atom-workspace atom-text-editor:not(.mini):not(.jumpy-jump-mode)':
  'ø': 'jumpy:toggle'
```

It works when I press it the first time, not the second. If I re-evaluate the `keymap.cson` file by adding a newline and saving it works, but only once. (This happens independently of which keymapping I choose for the command.)

Using the regular `SHIFT-ENTER` always works.

**Comment by endrebak** [comment]
Upon reloading the whole editor, remapping worked like a charm (seems like a general atom problem and not jumpy specific).

**Comment by DavidLGoldberg** [comment]
If I remember correctly there are some Atom peculiarities  surrounding this but, I actually have an open Jumpy issue related, I have a branch I may merge at some point.
https://github.com/DavidLGoldberg/jumpy/issues/56

I'll leave this issue closed however as the other is enough.

**Comment by DavidLGoldberg** [comment]
BTW, thanks for all of the awesome input / feedback.
