### ISSUE TITLE
Why is this line not given a jump-point?

### ISSUE THREAD

**Issue by tofagerl** [DavidLGoldberg/jumpy#73]
Great addon, I installed it an hour ago, and I can already tell that it's going to change my workflow within a week!

But I just found an instance where the addon failed me. As seen in the below screenshot, there are almost 20 areas in this very short file where I can jump to, but the one I wanted to jump to didn't have a shortcut. Is this due to the regex pattern jumpy uses? If so, why isn't there a selector for empty lines?
Could there be...?
![Screenshot of Atom where Jumpy disappoints me](https://www.evernote.com/shard/s3/sh/d5323699-76c6-4532-928e-52fda780ace4/665529cd84d92a1a/res/89cc4609-9d82-4cb6-b502-e18d9178c7db/skitch.png?resizeSmall&width=832)
<sup>I may have overemphasized the area I'm interested in, but I just got a free Evernote Premium license with a new tablet, so I wanted to try Skitch. Not impressed with their image sharing solution, but Dropbox isn't much better, so why bother moving it.</sup>

**Comment by DavidLGoldberg** [comment]
Hi, so thanks for downloading + the feedback.

I / everyone else definitely wants this feature.

There is some more work with refactors and pull requests I want to pull in to make this work, but in short, a few of the contributors and I want to remove the regex all together and handle end of lines, beginning, and empty spaces.

I am closing this as it's listed in other issues / pull requests :)

ps. I have a love hate relationship with evernote :\

**Comment by DavidLGoldberg** [comment]
The above proposed would handle those curlies too implicitly with end of line ones... 
might be a little different with vim-mode non vim-mode there, TBD.

**Comment by tofagerl** [comment]
Gotcha! Thanks :)
