### ISSUE TITLE
Jumpy breaks when tab is changed while in jump mode

### ISSUE THREAD

**Issue by misko321** [DavidLGoldberg/jumpy#75]
After pressing _shift+enter_ when jumpy's highlights appear, if you change tab and get back to the one that jumpy was started at, it doesn't work anymore. It is impossible to write anything or even exit Jumpy with _esc_.

**Comment by DavidLGoldberg** [comment]
Hi, Thanks for the report.

I'm looking to do a bunch of coding on this weekend coming up, as I'll be free.  Thanks.
