### ISSUE TITLE
Not showing for JS files

### ISSUE THREAD

**Issue by eighteyes** [DavidLGoldberg/jumpy#77]
I feel really bad about this, but it doesn't work for my JS files, works fine on others. I can get it to work intermittently, but not consistently. Any known conflicts?

├── aligner@0.17.1
├── angularjs@0.3.3
├── atom-beautify@0.28.15
├── atom-dark-fusion-syntax@0.7.0
├── atom-material-syntax@0.2.4
├── atom-material-ui@0.6.2
├── atom-polymer@0.10.1
├── atomatigit@1.5.5
├── auto-indent@0.5.0
├── autocomplete-modules@1.3.1
├── editor-stats@0.17.0
├── emmet@2.3.13
├── figlet@0.5.2
├── git-blame@0.4.7
├── goto@1.7.1
├── imdone-atom@1.1.49
├── indent-guide-improved@1.4.3
├── jumpy@2.0.10
├── language-diff@0.3.1
├── language-docker@1.1.3
├── language-html@0.42.0
├── linter@1.9.1
├── linter-jscs@3.1.2
├── linter-jshint@1.2.1
├── merge-conflicts@1.3.6
├── minimap@4.15.0
├── minimap-codeglance@0.4.2
├── mocha-test-runner@0.4.5
├── monokai-seti@0.7.0
├── node-debugger@1.1.9
├── nucleus-dark-ui@0.6.6
├── open-recent@2.3.0
├── package-list@0.1.2
├── pain-split@1.4.0
├── pigments@0.18.1
├── seti-syntax@0.4.0
├── seti-ui@0.8.0
├── seti-ui-red@0.13.0
├── solarized-seti-ui@0.8.6
├── sort-lines@0.12.0
├── term2@0.9.21
├── todo-manager@0.2.5
├── tree-view-git-status@0.2.2
└── turbo-javascript@1.1.5

**Comment by DavidLGoldberg** [comment]
Wow, I do a lot of JS work, (although mostly Coffee lately) haven't seen this yet!  Thanks for reporting!

Not sure when I'll get around to this, a bit busy this weekend.  My guess is it's one of the javascript packages you're using.. turbo-javascript perhaps? I haven't used that yet..

Thanks so much for letting me know!

**Comment by eighteyes** [comment]
I tried disabling almost all the packages, and it didn't work out. :(

On Fri, Oct 30, 2015 at 5:20 PM, David L. Goldberg <notifications@github.com

**Comment by DavidLGoldberg** [comment]
@eighteyes, Could you try disabling a few more?  I can't reproduce this on my install.

**Comment by DavidLGoldberg** [comment]
I can't reproduce any particular weird behavior with a JS file even after installing turbo-javascript, emmet, angularjs, and I already have the 2 linters you're using.

NOTE: I have been noticing unusual load times for the labels, with the new release that I am looking into!

BTW, are you using .js or .jsx?

Did you confirm that other file types work?

**Comment by eighteyes** [comment]
Your dedication to open source is commendable, I'll give it another shot.
Someone needs to make an extension conflict helper for Atom. :)

Yea, all the other file types I tried worked, I don't do jsx. I'm wondering
if something else is competing for the z-index, because they show up in the
dom.

**Comment by DavidLGoldberg** [comment]
Thanks!

Ah, very interesting, that they're in the dom.. 

BTW, it looks like a new release has slowed down jumpy 10x, and it's all in "drawLabel" so I have some work to do tonight or soon.. Might help to port it all to decorations and markers... (might not)

**Comment by eighteyes** [comment]
Found it. conflicts with indent-guide-improved. yay!

**Comment by DavidLGoldberg** [comment]
woahhh

**Comment by DavidLGoldberg** [comment]
I've been still trying to wrap up this performance improvements.. hopefully one of these days soon!

I'll take a look, maybe it's something I'm doing wrong.  Maybe I can that one we'll see.  Is it a good package?  (Just looked it up)... I just told a coworker about that idea.. haha I'll *definitely* try to fix it in that case... :+1:

**Comment by eighteyes** [comment]
It's not a great package, I just changed my stylesheet for substantially
the same thing. I'd just mark it as a conflict and move on.

**Comment by DavidLGoldberg** [comment]
Heh, clever.
