### ISSUE TITLE
Disable label fadein animation option in settings for better responsivness

### ISSUE THREAD

**Issue by eyalw** [DavidLGoldberg/jumpy#78]
Add 'Disable label animation' option in settings for better responsivness.
atm - i experience a small lag for big screens with many labels.

thanks!

**Comment by DavidLGoldberg** [comment]
I was going to make an issue, but one of the most recent patches dramatically slowed down performance.

Times are no where what they were (post 1.0 etc.)

I have a branch pretty far along to dramatically change how I do everything, using Atom's markers + decorations (some of the options we have today weren't available when I began Jumpy).

The guy working on semantic javascript said he noticed the same thing (kind of frustrating).

I'll leave this open until the performance is improved.  At the moment it's something like 10x slower.

:-(

I'll try to wrap it up this weekend.

**Comment by DavidLGoldberg** [comment]
As far as the style for this, you can override it in the Atom -> Open your style sheets.  Some instructions are on the readme, although I'm updating that as well with the new release.  Might want to just hang tight a few days :\

**Comment by eyalw** [comment]
thanks!


—
Eyal Wiener
