### ISSUE TITLE
I don't see any text high-light

### ISSUE THREAD

**Issue by polamin** [DavidLGoldberg/jumpy#79]
Now I can toggle jumpy but I can't see any text high-light

**Comment by DavidLGoldberg** [comment]
You need to give me more details.  I'm on the newest Atom / Jumpy and it works fine.  I *am* working on a new release that will improve performance, as the performance was affected by a recent Atom core release.

**Comment by DavidLGoldberg** [comment]
When you say text high-light you mean labels right?

Have you used Jumpy before with success?

**Comment by polamin** [comment]
Yes it's a label
This is my first time with jumpy
And it doesn't work

**Comment by DavidLGoldberg** [comment]
Have you restarted Atom once since you installed it?

**Comment by polamin** [comment]
Yes and try to reinstall jumpy doesn't work

**Comment by DavidLGoldberg** [comment]
Hmm, Can you open the inspector?

cmd + alt + i

And see if there's an error when you activate the hot key.  Also what about cmd + shift + p -> type jumpy toggle (or toggle jumpy I forget)

**Comment by DavidLGoldberg** [comment]
What OS are you on btw?

**Comment by DavidLGoldberg** [comment]
Want to double confirm newest version of Atom.  Atom is super weird with upgrading, have to click that check for newest I think.  For all I know there was a version in between a few recent released that it wasn't working on.  Been pretty stable since 1.0 aside from the performance.

**Comment by polamin** [comment]
Now I have something weird happen
Jumpy works on plain text file for example .txt or no extension file
But doesn't work with something like HTML JavaScript php css

I'm using osx

**Comment by DavidLGoldberg** [comment]
Ok, sounds like it's probably another package interfering...

**Comment by DavidLGoldberg** [comment]
So, if you take those files and click on the lower right, and change to plain text.. it should work again right?  Jumpy doesn't have anything language specific btw :\

Almost definitely some other package...

**Comment by DavidLGoldberg** [comment]
on command line you can do

`apm list`

Very useful.

**Comment by polamin** [comment]
Yes something like that but I'm using easy-motion-redux it's work
But I'm begging you don't leave me with this super slow package

**Comment by DavidLGoldberg** [comment]
unfortunately I don't know any command line way (I don't think there is one yet) to do a "disable" from apm yet.  Have to go into the settings (cmd +, ) and disable it in packages

**Comment by DavidLGoldberg** [comment]
(don't forget to do reloads after packages disabled)

**Comment by DavidLGoldberg** [comment]
Hah, I didn't know anyone forked that.  That's all after the sublime / vim easy motion stuff.  I thought that was way too complicated.  I was actually working on a jumpy for sublime when someone pointed me to vim motion heh

**Comment by DavidLGoldberg** [comment]
Jumpy's a bit easier to use / on the brain... and new branch is back to real fast 30 ms times.

**Comment by DavidLGoldberg** [comment]
(IMO of course heh)

**Comment by polamin** [comment]
It doesn't work if I change the bottom to plain text It doesn't work if I
copy my code to new file without extension too
It's only work with plain text that not a code

**Comment by DavidLGoldberg** [comment]
do you use vim-mode (just a survey, wish I knew the numbers)

**Comment by DavidLGoldberg** [comment]
hmm... I'm 99% sure Jumpy doesn't do anything with language or code :)

**Comment by polamin** [comment]
Built-in Atom packages (90)

├── about@1.1.0

├── archive-view@0.61.0

├── atom-dark-syntax@0.27.0

├── atom-dark-ui@0.51.0

├── atom-light-syntax@0.28.0

├── atom-light-ui@0.43.0

├── autocomplete-atom-api@0.9.2

├── autocomplete-css@0.11.0

├── autocomplete-html@0.7.2

├── autocomplete-plus@2.23.0

├── autocomplete-snippets@1.7.1

├── autoflow@0.26.0

├── autosave@0.23.0

├── background-tips@0.26.0

├── base16-tomorrow-dark-theme@1.0.0

├── base16-tomorrow-light-theme@1.0.0

├── bookmarks@0.38.0

├── bracket-matcher@0.79.0

├── command-palette@0.36.0

├── deprecation-cop@0.54.0

├── dev-live-reload@0.47.0

├── encoding-selector@0.21.0

├── exception-reporting@0.37.0

├── find-and-replace@0.189.0

├── fuzzy-finder@0.93.0

├── git-diff@0.57.0

├── go-to-line@0.30.0

├── grammar-selector@0.48.0

├── image-view@0.55.0

├── incompatible-packages@0.25.0

├── keybinding-resolver@0.33.0

├── language-c@0.49.0

├── language-clojure@0.18.0

├── language-coffee-script@0.43.0

├── language-csharp@0.11.0

├── language-css@0.34.0

├── language-gfm@0.81.0

├── language-git@0.10.0

├── language-go@0.39.0

├── language-html@0.42.0

├── language-hyperlink@0.15.0

├── language-java@0.16.0

├── language-javascript@0.98.0

├── language-json@0.17.1

├── language-less@0.28.3

├── language-make@0.19.0

├── language-mustache@0.13.0

├── language-objective-c@0.15.0

├── language-perl@0.30.0

├── language-php@0.32.0

├── language-property-list@0.8.0

├── language-python@0.41.0

├── language-ruby@0.60.0

├── language-ruby-on-rails@0.23.0

├── language-sass@0.42.0

├── language-shellscript@0.19.0

├── language-source@0.9.0

├── language-sql@0.19.0

├── language-text@0.7.0

├── language-todo@0.27.0

├── language-toml@0.16.0

├── language-xml@0.34.0

├── language-yaml@0.24.0

├── line-ending-selector@0.3.0

├── link@0.31.0

├── markdown-preview@0.156.0

├── metrics@0.53.0

├── notifications@0.61.0

├── one-dark-syntax@1.1.1

├── one-dark-ui@1.1.5

├── one-light-syntax@1.1.1

├── one-light-ui@1.1.5

├── open-on-github@0.39.0

├── package-generator@0.41.0

├── release-notes@0.53.0

├── settings-view@0.231.0

├── snippets@0.101.0

├── solarized-dark-syntax@0.39.0

├── solarized-light-syntax@0.23.0

├── spell-check@0.62.0

├── status-bar@0.80.0

├── styleguide@0.45.0

├── symbols-view@0.110.0

├── tabs@0.88.0

├── timecop@0.33.0

├── tree-view@0.195.0

├── update-package-dependencies@0.10.0

├── welcome@0.32.0

├── whitespace@0.32.0

└── wrap-guide@0.38.1


/Users/polaminsinghasuwich/.atom/packages (22)

├── atom-material-ui@0.8.0

├── autoclose-html@0.19.0

├── autocomplete-paths@1.0.2

├── autocomplete-php@0.3.7

├── color-picker@2.0.13

├── easy-motion-redux@0.0.4

├── editor-stats@0.17.0

├── file-icons@1.6.12

├── highlight-line@0.11.0

├── indent-guide-improved@1.4.4

├── jshint@1.8.3

├── jumpy@2.0.10

├── linter@1.11.3

├── minimap@4.16.2

├── minimap-pigments@0.1.7

├── native-ui@0.10.0

├── pigments@0.19.1

├── slime@1.4.0

├── smalls@0.1.8

├── sync-settings@0.6.0

├── travis-ci-status@0.18.0

└── vim-mode@0.63.0



AND YES I'M USING VIM MODE

**Comment by DavidLGoldberg** [comment]
Probably some other package doing something right?  I would be super grateful if you messed with disabling some :P   Maybe I'll give a go at installing the web ones... oh, someone found one the other day that broke jumpy.. it related to tab lines..

**Comment by DavidLGoldberg** [comment]
indent guide improved maybe!? can you try disabling that?

**Comment by DavidLGoldberg** [comment]
Yes, just checked the page taht's the one! that would explain the code aspect

**Comment by DavidLGoldberg** [comment]
last time the guy just figured that out all for me so I never made the code connection sorry!

**Comment by DavidLGoldberg** [comment]
It's funny, I had that idea, it *looks* like a great implementation, I'll reach out to the guy / try to PR it maybe

**Comment by DavidLGoldberg** [comment]
Here's the previous thread!
https://github.com/DavidLGoldberg/jumpy/issues/77

**Comment by polamin** [comment]
something weird happen again
If I shift+enter to toggle jumpy
then go to disable indent-guide-improved
Labels apear but but but I can't use it to navigate and can't close the
label
the only way to close label is just close the file and reopen and jumpy
doesn't again at all

**Comment by DavidLGoldberg** [comment]
well after you disable the indent guide please do a restart, btw, instead of a real restart

did you know about:

<kbd>cmd</kbd>+<kbd>cntl</kbd>+<kbd>alt</kbd>+<kbd>l</kbd> <--lower case L for load

**Comment by DavidLGoldberg** [comment]
It just refreshes the engine (I use it randomly if atom gets sluggish!!!!!!!!!!!!!)

**Comment by polamin** [comment]
OMG IT'S WORK THANK YOU FOR THIS FREAKING FAST PACKAge

**Comment by DavidLGoldberg** [comment]
Trust me, it's slow as shit right now.  It'll be faster REAL soon, I have one frustrating bug to get through on the new branch.

**Comment by DavidLGoldberg** [comment]
Thanks for taking the time! :+1:  :-)

**Comment by polamin** [comment]
NO I have to thanks you for full support and it's free
OMG I want to help you to fix your package buy I'm not that expert

**Comment by DavidLGoldberg** [comment]
Haha, no worries, appreciate the support! I'm so close, got a lot done this weekend.  I'll try to finish soon though, next couple of days.
