### ISSUE TITLE
can't find the keybindings in the setting

### ISSUE THREAD

**Issue by linzerui** [DavidLGoldberg/jumpy#86]
I remember there was a checkbox to enable or disable the keybindings in the setting but now I can't find it. that means I hit shift + enter does not work.
I then add the keymap to my file:

    '.editor:not(.mini).vim-mode-plus:not(.insert-mode):not(.jumpy-jump-mode)':
      'f': 'jumpy:toggle'

now I hit `f` can active the jump mode. but I can not jump under the jump mode! And `esc` can not cancel the jump mode either.
try to restart and install jumpy again but it does not work. 

I don't know where is the `checkbox`😥

**Comment by DavidLGoldberg** [comment]
I'll take a quick peek at this, this weekend.

**Comment by DavidLGoldberg** [comment]
Sorry I never got to this one (forgot).

Is this still an issue for you.

My current keymap has:
'atom-text-editor:not(.mini).vim-mode:not(.insert-mode):not(.jumpy-jump-mode)':
  'f': 'jumpy:toggle'

**Comment by DavidLGoldberg** [comment]
Oh, you probably never updated it with the README.md's new code block.
This was one of the reasons for the 3.0 bump, as there had to be some breaking changes with API changes etc.  Sorry about that!!!

I hope we can get jumpy up and running for you guys @linzerui @greena13

**Comment by DavidLGoldberg** [comment]
@linzerui, @greena13, Either of you still having this issue?

**Comment by linzerui** [comment]
It works now 😁 Thanks a lot !

**Comment by DavidLGoldberg** [comment]
@linzerui Thanks!!!
