### ISSUE TITLE
Make Selection

### ISSUE THREAD

**Issue by antonkluev** [DavidLGoldberg/jumpy#89]
Is it possible to make a selection between jumps?

**Comment by DavidLGoldberg** [comment]
Yes.

Assuming you mean start highlight and jump to end highlight position?

Try it.

By the way, if you use vim-mode.  It works in both visual and insert mode.

**Comment by antonkluev** [comment]
thanks! btw. the vimari plugin in safari open link in current tab if typing the regular way, but if you press shift while first and second or only second key it will be opened in the new tab. May be it could be the new feature? you press shit while pressing a key combo and jumps to the new location but directly with connection!
